dependencies:
- name: exposecontroller
  version: 2.3.58
  repository: https://chartmuseum.build.cd.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.58
  repository: https://chartmuseum.build.cd.jenkins-x.io
  alias: cleanup
- name: activiti-cloud-full-example
  version: 0.2.1
  repository: https://activiti.github.io/activiti-cloud-charts/